// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentKind } from "./SegmentKind";

/**
 * 命令的一段，界面按段换行展示
 */
export type ArgSegment = { kind: SegmentKind, args: Array<string>, };
