// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioStream = { index: number, codec: string, profile?: string, channels: number, channelLayout: string, sampleRate: number, bitrate?: number, language?: string, title?: string, isDefault: boolean, lossless: boolean, atmos: boolean, dtsX: boolean, durationSec?: number, };
