// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCodec } from "./AudioCodec";
import type { StreamAction } from "./StreamAction";
import type { TrackRole } from "./TrackRole";

export type AudioTrackPlan = { 
/**
 * 源音轨的流序号
 */
sourceIndex: number, action: StreamAction, codec?: AudioCodec, bitrateKbps?: number, channels?: number, title?: string, role: TrackRole, };
