// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildFlag = { name: string, present: boolean, 
/**
 * 缺失时影响的功能
 */
affects: string, };
