// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildFlag } from "./BuildFlag";
import type { DeviceProbe } from "./DeviceProbe";
import type { EncoderProbe } from "./EncoderProbe";
import type { EnvStatus } from "./EnvStatus";
import type { ExternalTool } from "./ExternalTool";
import type { GpuInfo } from "./GpuInfo";
import type { LocateSource } from "./LocateSource";
import type { Platform } from "./Platform";
import type { TonemapProbe } from "./TonemapProbe";

export type Capabilities = { status: EnvStatus, 
/**
 * 状态的中文说明；就绪时为空
 */
statusDetail: string, ffmpegPath: string, ffprobePath: string, locateSource?: LocateSource, 
/**
 * 没找到时列出查找过的目录，便于用户排查
 */
searched: Array<string>, 
/**
 * 不影响使用的提示，如 ffprobe 与 ffmpeg 版本不一致
 */
notes: Array<string>, 
/**
 * ffmpeg 自报的版本串，如 `9.0.1-full_build-www.gyan.dev`
 */
version: string, 
/**
 * 推断出的发行版本号，如 `9.0.1`；git 构建按库版本推断
 */
versionNumber: string, buildSource: string, buildFlags: Array<BuildFlag>, encoders: Array<EncoderProbe>, hwaccels: Array<string>, devices: Array<DeviceProbe>, tonemap: Array<TonemapProbe>, 
/**
 * libx265 支持 `-dolbyvision` 且版本满足要求
 */
dolbyVisionEncode: boolean, doviSplit: boolean, external: Array<ExternalTool>, gpus: Array<GpuInfo>, platform: Platform, probedAt: string, 
/**
 * 缓存 key：路径 + 修改时间 + 版本 + GPU + 驱动
 */
fingerprint: string, };
