// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorRange } from "./ColorRange";
import type { HdrKind } from "./HdrKind";

export type ColorInfo = { primaries: string, transfer: string, space: string, range: ColorRange, hdrKind: HdrKind, };
