// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * "为什么这么选"的一条理由
 */
export type Decision = { field: string, value: string, reason: string, severity: Severity, };
