// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 第 2 层硬件设备初始化的结果
 */
export type DeviceProbe = { 
/**
 * ffmpeg 的 hwdevice 类型名：qsv / cuda / d3d11va / vulkan / opencl / videotoolbox …
 */
id: string, available: boolean, error?: string, };
