// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";
import type { EncoderId } from "./EncoderId";
import type { QualityValues } from "./QualityValues";
import type { RateControlKind } from "./RateControlKind";
import type { Vendor } from "./Vendor";

export type EncoderMeta = { id: EncoderId, vendor: Vendor, codec: Codec, hardware: boolean, 
/**
 * 质量参数名：CRF / global_quality / CQ / QP / q:v
 */
param: string, min: number, max: number, lowerIsBetter: boolean, presets: Array<string>, quality: QualityValues, rateControls: Array<RateControlKind>, 
/**
 * 会把 HDR10 静态元数据写进码流
 */
writesHdr10: boolean, };
