// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VidForge 认识的全部视频编码器。序列化值就是 ffmpeg 的编码器名。
 */
export type EncoderId = "libx264" | "libx265" | "libsvtav1" | "h264_qsv" | "hevc_qsv" | "av1_qsv" | "h264_nvenc" | "hevc_nvenc" | "av1_nvenc" | "h264_amf" | "hevc_amf" | "av1_amf" | "h264_videotoolbox" | "hevc_videotoolbox";
