// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";
import type { EncoderId } from "./EncoderId";
import type { FailureKind } from "./FailureKind";
import type { Vendor } from "./Vendor";

/**
 * 第 3 层真实试编码的结果
 */
export type EncoderProbe = { id: EncoderId, vendor: Vendor, codec: Codec, usable: boolean, tenBit: boolean, error?: string, failure?: FailureKind, };
