// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncoderMeta } from "./EncoderMeta";
import type { StandardFpsMeta } from "./StandardFpsMeta";

export type EngineMeta = { encoders: Array<EncoderMeta>, standardFps: Array<StandardFpsMeta>, minKbps: number, maxKbps: number, };
