// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ffmpeg 的整体状态，决定界面是否能开始转码
 */
export type EnvStatus = "ready" | "probing" | "missing" | "too_old" | "broken";
