// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Estimate = { sizeMin: number, sizeMax: number, timeMinSec: number, timeMaxSec: number, 
/**
 * 输出 / 源 的体积比，取区间中值
 */
ratio: number, 
/**
 * 预计的平均视频码率（bps）；原样封装时是源的视频码率。界面切到按码率编码时以它为起始值
 */
videoBps: number, };
