// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 硬件编码失败的分类，决定回退动作（设计文档 4.2）
 */
export type FailureKind = "device_missing" | "capability" | "param" | "resource" | "not_built" | "unknown";
