// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FidelityKind } from "./FidelityKind";
import type { FidelityState } from "./FidelityState";
import type { Fix } from "./Fix";

export type FidelityItem = { kind: FidelityKind, label: string, state: FidelityState, detail: string, fixes: Array<Fix>, };
