// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FidelityState = "achievable" | "needs_change" | "impossible" | "not_applicable";
