// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FidelityKind = "dolbyVision" | "hdr10" | "hdr10plus" | "lossless" | "allAudio" | "allSubtitles" | "chapters" | "tenBit";
