// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 用户勾选的"尽量保留"项
 */
export type FidelityRequest = { dolbyVision: boolean, hdr10: boolean, hdr10plus: boolean, lossless: boolean, allAudio: boolean, allSubtitles: boolean, chapters: boolean, tenBit: boolean, };
