// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FpsInsight = { sourceFrames: number, targetFrames: number, duplicated: number, dropped: number, targetFps: number, };
