// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帧率策略（设计文档 4.9）
 */
export type FpsPolicy = { "kind": "keep" } | { "kind": "cfr", fps: number, } | { "kind": "cap", max: number, };
