// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MasteringPrimaries } from "./MasteringPrimaries";

/**
 * HDR10 静态元数据。数值一律是已求值的浮点（nits / CIE xy），不保留有理数字符串：
 * HEVC 与 AV1 的定点分母不同（技术事实文档 2.2 节），字符串比对必然误判。
 */
export type Hdr10Metadata = { maxLuminance: number, minLuminance: number, maxCll?: number, maxFall?: number, masteringPrimaries: MasteringPrimaries, };
