// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入失败的文件
 */
export type ImportFailure = { path: string, 
/**
 * 中文原因
 */
reason: string, };
