// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入失败的文件
 */
export type ImportFailure = { path: string, 
/**
 * 给用户看的原因（按界面语言）
 */
reason: string, 
/**
 * ffprobe 原文，界面上可展开查看
 */
detail?: string, };
