// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入进度事件
 */
export type ImportProgress = { done: number, total: number, 
/**
 * 刚分析完的文件名
 */
current: string, };
