// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";
import type { MediaInfo } from "./MediaInfo";

export type ImportResult = { media: Array<MediaInfo>, failures: Array<ImportFailure>, 
/**
 * 文件夹里扩展名不像视频、被跳过的文件数
 */
skipped: number, 
/**
 * 被跳过的文件的扩展名（小写、带点；没有扩展名时为空串），界面据此说明跳过了什么
 */
skippedExts: Array<string>, };
