// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncoderId } from "./EncoderId";
import type { JobEvent } from "./JobEvent";
import type { JobProgress } from "./JobProgress";
import type { JobStatus } from "./JobStatus";
import type { MediaInfo } from "./MediaInfo";
import type { ReportItem } from "./ReportItem";
import type { TranscodePlan } from "./TranscodePlan";

export type Job = { id: string, media: MediaInfo, 
/**
 * 实际执行的计划（回退后会换编码器）
 */
plan: TranscodePlan, 
/**
 * 实际执行的命令（两遍编码时是第二遍），写入临时文件
 */
args: Array<string>, firstPass?: Array<string>, 
/**
 * 最终文件路径
 */
outputPath: string, status: JobStatus, progress: JobProgress, encoderUsed: EncoderId, events: Array<JobEvent>, 
/**
 * ffmpeg 输出的最后若干行
 */
log: Array<string>, report?: Array<ReportItem>, startedAt?: number, finishedAt?: number, outputSize?: number, 
/**
 * 已经执行过的次数（含回退重跑）
 */
attempts: number, };
