// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventLevel } from "./EventLevel";

/**
 * 任务时间线上的一条记录：预检、回退、完成、失败原因……
 */
export type JobEvent = { 
/**
 * Unix 毫秒
 */
at: number, level: EventLevel, message: string, };
