// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventLevel } from "./EventLevel";

/**
 * 任务时间线上的一条记录：预检、回退、完成、失败原因……
 */
export type JobEvent = { 
/**
 * Unix 毫秒
 */
at: number, level: EventLevel, message: string, 
/**
 * ffmpeg 原文，界面上可展开查看（需求 F-9.4：不直接抛原始报错）
 */
detail?: string, };
