// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobProgress } from "./JobProgress";

/**
 * 运行中的进度推送，只带变化的部分
 */
export type JobProgressEvent = { id: string, progress: JobProgress, };
