// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobProgress = { 
/**
 * 0–100；两遍编码按两遍合并
 */
percent: number, 
/**
 * 当前这一遍已处理到的时间点
 */
outTimeSec: number, 
/**
 * 实时倍速（平滑后）
 */
speed: number, fps: number, sizeBytes: number, 
/**
 * 剩余时间；开头几秒速度不可信，不给
 */
etaSec?: number, dupFrames: number, dropFrames: number, 
/**
 * 两遍编码时正在跑第几遍
 */
pass?: number, };
