// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 在哪一级找到的 ffmpeg（设计文档 5.1）
 */
export type LocateSource = "user" | "bundled" | "path" | "registry" | "common";
