// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioStream } from "./AudioStream";
import type { SourceHint } from "./SourceHint";
import type { SubtitleStream } from "./SubtitleStream";
import type { VideoStream } from "./VideoStream";

export type MediaInfo = { 
/**
 * 由规范化路径派生，同一文件重复导入得到同一个 id
 */
id: string, path: string, name: string, 
/**
 * 简短容器名：mp4 / mov / mkv / m2ts …
 */
container: string, durationSec: number, sizeBytes: number, 
/**
 * 总码率 bps
 */
bitrate: number, video: Array<VideoStream>, audio: Array<AudioStream>, subtitle: Array<SubtitleStream>, chapters: number, attachments: number, 
/**
 * MP4 / MOV 的封面图（attached_pic 视频流）张数，没有时为空。现在的命令不带封面，推荐理由与校验会标出
 */
covers?: number, sourceHint: SourceHint, 
/**
 * 拍摄设备，如 "Apple iPhone 16 Pro"
 */
device?: string, 
/**
 * 通过文件夹导入时的根目录，"保留源目录结构"据此计算相对路径
 */
importRoot?: string, };
