// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { Estimate } from "./Estimate";
import type { FidelityItem } from "./FidelityItem";
import type { FpsInsight } from "./FpsInsight";
import type { TranscodePlan } from "./TranscodePlan";

export type PlanResult = { plan: TranscodePlan, decisions: Array<Decision>, fidelity: Array<FidelityItem>, args: Array<string>, estimate: Estimate, fpsInsight?: FpsInsight, 
/**
 * 源码率已低于目标时的"不建议转码"提示
 */
notWorthIt?: string, };
