// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArgSegment } from "./ArgSegment";
import type { Decision } from "./Decision";
import type { Estimate } from "./Estimate";
import type { FidelityItem } from "./FidelityItem";
import type { FpsInsight } from "./FpsInsight";
import type { TranscodePlan } from "./TranscodePlan";

export type PlanResult = { plan: TranscodePlan, decisions: Array<Decision>, fidelity: Array<FidelityItem>, args: Array<string>, 
/**
 * 与 args 相同的命令，按段分组，界面按段换行展示
 */
segments: Array<ArgSegment>, 
/**
 * 两遍编码的第一遍命令（只分析、不输出文件）；其余模式为空
 */
firstPass?: Array<string>, 
/**
 * 响度标准化的测量命令，每条要标准化的音轨一条；执行时先跑它们，再把测得的值带进主命令
 */
loudnessMeasure?: Array<Array<string>>, estimate: Estimate, fpsInsight?: FpsInsight, 
/**
 * 源码率已低于目标时的"不建议转码"提示
 */
notWorthIt?: string, };
