// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 探测进度事件
 */
export type ProbeProgress = { 
/**
 * 当前阶段的中文说明
 */
stage: string, done: number, total: number, };
