// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 四个质量档位在某个编码器上的原生数值
 */
export type QualityValues = { lossless: number, high: number, standard: number, small: number, };
