// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 界面对队列的操作
 */
export type QueueOp = { "kind": "pause", id: string, } | { "kind": "resume", id: string, } | { "kind": "cancel", id: string, } | { "kind": "retry", id: string, } | { "kind": "remove", id: string, } | { "kind": "move", id: string, delta: number, } | { "kind": "set_paused", paused: boolean, } | { "kind": "clear_finished" };
