// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaInfo } from "./MediaInfo";
import type { TranscodePlan } from "./TranscodePlan";

/**
 * 加入队列的一项：界面上的素材与计划。命令由后端按计划重新生成，不信任前端的参数
 */
export type QueueItem = { media: MediaInfo, plan: TranscodePlan, };
