// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Job } from "./Job";

/**
 * 队列的完整状态，结构变化（增删、换序、状态改变）时整体推送
 */
export type QueueSnapshot = { jobs: Array<Job>, 
/**
 * 全部暂停：进行中的任务挂起，排队的不开始
 */
paused: boolean, };
