// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 码率控制（需求 F-3.3）。码率单位都是 kbps
 */
export type RateControl = { "kind": "quality" } | { "kind": "bitrate", kbps: number, } | { "kind": "capped", kbps: number, } | { "kind": "two_pass", kbps: number, };
