// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 码率控制方式（不含数值），界面据此列出编码器支持的选项
 */
export type RateControlKind = "quality" | "bitrate" | "capped" | "two_pass";
