// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 输出校验的一项（设计文档 4.8）
 */
export type ReportItem = { label: string, expected: string, actual: string, ok: boolean, };
