// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Scenario = "archive" | "collection" | "streaming" | "mobile" | "social" | "smallest" | "editing" | "remux";
