// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 命令段的类别。界面按语言显示它的名字
 */
export type SegmentKind = "global" | "input" | "video" | "filter" | "fps" | "map" | "audio" | "subtitle" | "mux" | "output";
