// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AfterAction } from "./AfterAction";
import type { ConflictPolicy } from "./ConflictPolicy";
import type { Lang } from "./Lang";
import type { ThemePref } from "./ThemePref";

export type Settings = { 
/**
 * 用户指定的 ffmpeg 目录或可执行文件；None 表示自动查找
 */
ffmpegPath?: string, 
/**
 * 输出目录；None 表示源文件旁的 VidForge 文件夹
 */
outputDir?: string, namingTemplate: string, keepTree: boolean, conflict: ConflictPolicy, after: AfterAction, hwEncode: boolean, hwDecode: boolean, cpuSlots: number, gpuSlots: number, notify: boolean, language: Lang, theme: ThemePref, 
/**
 * 首次启动引导已经走完（需求 F-9.5）
 */
onboarded: boolean, };
