// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitleStream = { index: number, codec: string, language?: string, title?: string, 
/**
 * PGS / VobSub / DVB 等图形字幕：MP4 装不下
 */
imageBased: boolean, };
