// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 色调映射管线不可用的原因（界面文字由它按语言生成）
 */
export type TonemapBlock = { "kind": "not_built", what: string, } | { "kind": "device", device: string, error: string, } | { "kind": "mac_only" } | { "kind": "trial_failed", error: string, };
