// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToneMapPipeline } from "./ToneMapPipeline";
import type { TonemapBlock } from "./TonemapBlock";

export type TonemapProbe = { id: ToneMapPipeline, available: boolean, 
/**
 * 可用时是这条管线的特点，不可用时是原因
 */
note: string, block?: TonemapBlock, };
