// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToneMapPipeline } from "./ToneMapPipeline";

export type TonemapProbe = { id: ToneMapPipeline, available: boolean, note: string, };
