// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMode } from "./AudioMode";
import type { AudioTrackPlan } from "./AudioTrackPlan";
import type { Container } from "./Container";
import type { FidelityRequest } from "./FidelityRequest";
import type { Scenario } from "./Scenario";
import type { SubtitleMode } from "./SubtitleMode";
import type { VideoPlan } from "./VideoPlan";

export type TranscodePlan = { scenario: Scenario, video: VideoPlan, audio: Array<AudioTrackPlan>, audioMode: AudioMode, subtitles: SubtitleMode, container: Container, fidelity: FidelityRequest, };
