// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";
import type { DoviAction } from "./DoviAction";
import type { EncoderId } from "./EncoderId";
import type { FpsPolicy } from "./FpsPolicy";
import type { HdrAction } from "./HdrAction";
import type { QualityTier } from "./QualityTier";
import type { RateControl } from "./RateControl";
import type { ResolutionPreset } from "./ResolutionPreset";
import type { StreamAction } from "./StreamAction";
import type { ToneMapPipeline } from "./ToneMapPipeline";

export type VideoPlan = { action: StreamAction, codec: Codec, encoder: EncoderId, 
/**
 * 为 true 时由引擎按场景与能力选择编码器
 */
encoderAuto: boolean, quality: QualityTier, 
/**
 * 当前编码器下的原生质量数值（CRF / CQ / global_quality …）
 */
qualityValue: number, rateControl: RateControl, preset: string, bitDepth: 8 | 10, resolution: ResolutionPreset, fps: FpsPolicy, hdrAction: HdrAction, tonemap?: ToneMapPipeline, dovi: DoviAction, gop?: number, 
/**
 * 追加到 `-x265-params` 的原始串
 */
extraParams?: string, 
/**
 * 附加 ffmpeg 参数（支持引号）
 */
extraArgs?: string, };
