// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帧率控件需要的、依赖素材的建议
 */
export type VideoHints = { 
/**
 * 打开"转为固定帧率"时的推荐目标
 */
recommendedFps: number, 
/**
 * 帧率波动剧烈（录屏类），转 CFR 会复制大量帧
 */
extremeVfr: boolean, };
