// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帧率与码率控件需要的、依赖素材的建议
 */
export type VideoHints = { 
/**
 * 打开"转为固定帧率"时的推荐目标（源帧率读不出时为 30）
 */
recommendedFps: number, 
/**
 * 固定帧率的上限，即源的帧率（不提帧率）；源帧率读不出时为空，不封顶
 */
maxFps?: number, 
/**
 * 帧率波动剧烈（录屏类），转 CFR 会复制大量帧
 */
extremeVfr: boolean, 
/**
 * 源视频码率（kbps），未知时为空。目标码率不会高于它
 */
sourceKbps?: number, };
