// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInfo } from "./ColorInfo";
import type { DoviInfo } from "./DoviInfo";
import type { Hdr10Metadata } from "./Hdr10Metadata";

export type VideoStream = { index: number, codec: string, profile?: string, width: number, height: number, 
/**
 * 实际平均帧率
 */
fpsAvg: number, 
/**
 * 名义帧率（r_frame_rate）
 */
fpsNominal: number, isVfr: boolean, bitDepth: 8 | 10 | 12, pixFmt: string, bitrate?: number, color: ColorInfo, hdr10?: Hdr10Metadata, dolbyVision?: DoviInfo, hdr10plus: boolean, 
/**
 * 显示旋转角度（度），来自 Display Matrix；宽高是编码尺寸
 */
rotation: number, frameCount?: number, };
